// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Donut {
    count:   number;
    results: Result[];
}

export interface Result {
    id:   number;
    ref:  string;
    name: string;
}
